### ISSUE TITLE
HTTPS connection fails

### ISSUE THREAD

**Issue by cani1989** [tfonfara/RemoteForTautulli-Issues#1]
### New Issue Checklist

- [x] My issue is related to the [Remote for Tautulli](https://itunes.apple.com/app/id1343177312) app, report issues for Tautulli [here](https://github.com/Tautulli/Tautulli-Issues/issues)
- [x] I updated Remote for Tautulli to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/tfonfara/RemoteForTautulli-Issues/issues)

### Description

Fails to add server whether it is HTTP or HTTPS on a seedbox. However, it works just fine with another server.
I can upload the logs, but I cannot see them myself to know what's wrong.

### Steps to Reproduce

1. QR and Manual data both fails when adding server

**Expected behavior:** Success

**Actual behavior:** Fails to add

### Logs

Uploaded with nr. 55614

### Versions

All the latest.

**Comment by tfonfara** [comment]
In your logs I can only see another issue that is already fixed for the next version. I added more logging during the adding process, please try again once the upcoming 1.3.0 is available (hopefully next week) and upload the logs again. Thanks a lot!

**Comment by cani1989** [comment]
I updated the app to 1.3.0 and it still doesn't work. New logs are 40817

**Comment by tfonfara** [comment]
Unfortunately I cannot see any connection attempts in the logs. Did you try to reconnect with the new version? I just validated that logging is working as expected.

**Comment by cani1989** [comment]
All is the latest versions. App version 1.3.0.147

I tried manual typing. Error logs: 29325.

**Comment by tfonfara** [comment]
I just found something in the logs, but from 25.6. did you try to connect on that date as well?
First thing I noticed is, you're connection to http://172.17.x.x:32400. Is this a static external ip address? The port looks like this is a plex server not a Tautulli server.
The request run into timeout when you tried that.

**Comment by cani1989** [comment]
I tried some different stuff on that date. It's was wrong, I know.

It's dynamic IP and I tried the URL https://river.seedhost.eu/sjoveren/plexpy together with the proper token and credentials. Doesn't work.

**Comment by cani1989** [comment]
But the QR code is non responsive.. shouldn't I get an error message?

**Comment by tfonfara** [comment]
Ah, there the issue, the url parser currently fails for this kind of urls (multiple directories). I‘ll provide a fix for that with next version.

**Comment by cani1989** [comment]
Great :) I hope this will fix it.

**Comment by cani1989** [comment]
It works!

**Comment by tfonfara** [comment]
Perfect 👍
